### ISSUE TITLE
events.js:72         throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by xiaoliuzi** [xiaoliuzi/netlib_demo#1]
```

xlz@ubuntu:~/test$ node s.js
Random Number Generator Running...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at Object.<anonymous> (/home/xlz/test/s.js:48:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
xlz@ubuntu:~/test$ vi s.js
xlz@ubuntu:~/test$ node s.js
```

**Comment by xiaoliuzi** [comment]
http://blog.csdn.net/dqjyong/article/details/26966931

经过一番排查，然来时端口已经被占用了，所以解决方法有两种：
1. 需改nodejs中的侦听端口，如将默认的80端口改成8080端口；
1. 找到已经占用nodejs端口的应用，然后杀掉该应用，最后重启nodejs。
